#import "./fragments/pokemon.fragment.gql"

query PokemonConnection($limit: Int, $offset: Int) {
  pokemons(query: { limit: $limit, offset: $offset }) {
    edges {
      ...pokemonAtrinutes
    }
  }
}
