#import "./fragments/pokemon.fragment.gql"

input PokemonFilterInput {
  isFavorite: Boolean
}

query PokemonConnection($limit: Int, $offset: Int, $filter: PokemonFilterInput) {
  pokemons(query: { limit: $limit, offset: $offset, filter: $filter }) {
    edges {
      ...pokemonAtributes
    }
  }
}
